---
title: "About this Website"
author:
- William Howard [Beasley](https://scholar.google.com/citations?user=ffsJTC0AAAAJ) (Howard Live Oak LLC, Norman)
- Joseph Lee [Rodgers](https://www.vanderbilt.edu/psychological_sciences/bio/joe-rodgers) (Vanderbilt University, Nashville)
- David [Bard](https://medicine.ouhsc.edu/academic-departments/pediatrics/sections/developmental-behavioral-pediatrics/faculty/david-bard-phd) (University of Oklahoma Health Sciences Center, OKC)

- Michael D. [Hunter](https://hhd.psu.edu/contact/michael-hunter) (Pennsylvania State University)
- S. Mason [Garrison](https://scholar.google.com/citations?user=5to21boAAAAJ) (Wake Forest University)
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{About this Website}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Components
=============================

This website is maintained by the [Joe Rodgers](https://www.vanderbilt.edu/psychological_sciences/bio/joe-rodgers) NLSY Sibling Research Team (see the [collaborators](https://nlsy-links.github.io/NlsyLinks/articles/collaborators.html) page for more details)

The website is hosted on [GitHub Pages](https://pages.github.com/).  It is built with [Jekyll](https://jekyllrb.com/) and [R Markdown](https://rmarkdown.rstudio.com/) (and heavily relied on the latter when forming the site's structure).  The majority of the static reports are created with  [knitr](https://yihui.org/knitr/), while the interactive reports are created with [Shiny](https://shiny.posit.co/); both use
[R](https://www.r-project.org/) as a foundation.

Historical Archives
=============================

To increase transparency and promote reproducibility, this website and software components are assigned a unique [DOI](https://www.doi.org/) (digital object identifier) after each substantial modification.  Each major version is archived (and [available for download indefinitely](https://zenodo.org/search?ln=en&p=MReportingPublic)) on a third-party site --where we cannot modify it.  See the [Software and Support](https://nlsy-links.github.io/NlsyLinks/articles/software-and-support.html) page for the DOIs of each component; all previous archives associated with the current project can be found by [searching the Zenodo site](https://zenodo.org/search?q=NlsyLinks&l=list&p=1&s=10&sort=bestmatch
).

Support and Code Collaboration
=============================

Our [support forums](https://github.com/LiveOak/NlsyLinks/issues) are intended to cover all aspects of this project, not just software.

Interested collaborators are welcome to propose changes or [submit an issue](https://github.com/LiveOak/NlsyLinks/issues) on our public [GitHub repository](https://github.com/LiveOak/NlsyLinks).  If you're new to GitHub, see the "Collaborating" section half-way down their [help site](https://support.github.com), or post a comment to us below.
