---
title: "Publications involving the kinship links"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Publications involving the kinship links}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The following publication list includes research products that used the NLSY79 or NLSY-Children/Young Adult kinship links. Note that research presentations have not been included on this list, except for those that occurred during the course of the two most recent NIH grants (2011-2014; 2017-2021). Otherwise, journal articles, book chapters, and theses/dissertations, are included within this list.

We have been distributing the NLSY kinship links for close to two decades, and only began collecting this archive of articles around ten years ago. There are likely some additional publications based on the kinship links of which we are not aware. If you know of such papers, please bring them to our attention.

Researchers and grad students interested using the [NLSY](https://www.nlsinfo.org/) for Behavior Genetics and family research, please start with our 2016 article, [*The NLSY Kinship Links: Using the NLSY79 and NLSY-Children Data to Conduct Genetically-Informed and Family-Oriented Research*](https://link.springer.com/article/10.1007/s10519-016-9785-3).

Articles and Book Chapters
=============================

2011 - Present
-----------------------------

<ol>

<li value=79><cite> Hunter, M. D., Garrison, S. M., Burt, S. A., & Rodgers, J. L.  (2021).  The analytic identification of variance component models common to behavior genetics.  Behavior Genetics. doi:10.1007/s10519-021-10055-x180)</cite> (NLSY79)</li>

<li value=78><cite> O’Keefe P. & Rodgers, J.L. (2020). A simulation study of bootstrap approaches to estimate confidence intervals in DeFries–Fulker regression models (with application to the heritability of BMI changes in the NLSY). Behavior Genetics,50, 127–138. doi.org/10.1007/s10519-020-09993-9</cite> (NLSY79)</li>

<li value=77><cite> Briley, D. A.  (2020).  Behavior genetic approaches for situation research.  Pp. 25-39 in J. F. Rauthmann, R. A. Sherman, & D. C. Funder (Eds) The Oxford Handbook of Psychological Situations.  New York, NY:  Oxford University Press.</cite> (General treatment)</li>
  
<li value=76><cite>Connelly, E. J.  (2020).  Further evaluating the relationship between adverse childhood experiences, antisocial behavior, and violent victimization: A sibling-comparison analysis,  Youth Violence and Juvenile Justice, 18, 3-23.</cite>   (NLSY79)</li>  
  
<li value=75><cite>Rodgers, J. L., Garrison, S. M., O’Keefe, P., Bard, D. E., Hunter, M. D., Beasley, W. H., van den Oord, E. (2019).   Responding to a 100-year-old challenge from Fisher:  A biometrical analysis of adult height in the  NLSY data using only cousin pairs.  Behavior Genetics, 49, 444-454.</cite>  (NLSYC/YA)</li>  
  
<li value=74><cite>Garrison, S. M., & Rodgers, J. L. (2019). Decomposing the Causes of the Socioeconomic Status-Health Gradient with Biometrical Modeling. *Journal of Personality and Social Psychology*.</cite> (NLSY79)</li>

  
<li value=73><cite>Kavish, N., Connolly, E. J., & Boutwell, B. B. (2019). Genetic and environmental contributions to the association between violent victimization and major depressive disorder. *Personality and Individual Differences*. <span class="doi">doi: 10.1016/j.paid.2018.05.034</span></cite> (NLSY79, NLSYC/YA)</li>

<li value=72><cite>Johansson, O. (2017). Special Needs Children and Sibling Spillover Effects: Evidence from the National Longitudinal Study of Youth. (Unpublished Thesis) </cite> (NLSYC)</li>

<li value=71><cite>Little, C. W., Haughbrook, R., & Hart, S. A. (2017). Cross-study differences in the etiology of reading comprehension: A meta-analytical review of twin studies. *Behavior genetics*, 47(1), 52-76. <span class="doi">doi: 10.1007/s10519-016-9810-6</span></cite> (NLSYC)</li>

<li value=70><cite>Garrison, S. M., & Rodgers, J. L. (2017). Decomposing the Causes of the Socioeconomic Status-Health Gradient with Biometrical Modeling. *Multivariate Behavioral Research*, 52(1), 118-119, https://osf.io/xbkja/.</cite> (NLSY79)</li>

<li value=69><cite>Boutwell, B. B., Connolly, E. J., Barbaro, N., Shackelford, T. K., Petkovsek, M., & Beaver, K. M. (2017). On the genetic and environmental reasons why intelligence correlates with criminal victimization.  *Intelligence*. <span class="doi">doi: 10.1101/113712</span></cite> (NLSYC)</li>

<li value=68><cite>Hadd, A. R. & Rodgers, J. L. (2017). Intelligence, income, and education as potential influences on a child's home environment: A (maternal) sibling-comparison design. *Developmental Psychology*. <span class="doi">doi: 10.1037/dev0000320</span></cite> (NLSY79; NLSYC)</li>

<li value=67><cite>Goodnight, J. A., Donahue, K. L., Waldman, I. D., Van Hulle, C. A., Rathouz, P. J., Lahey, B. B., & D'Onofrio, B. M. (2016). Genetic and environmental contributions to associations between infant fussy temperament and antisocial behavior in childhood and adolescence. *Behavior Genetics*. <span class="doi">doi: 10.1007/s10519-016-9794-2</span></cite> (NLSY79; NLSYC)</li>

<li value=66><cite>Garrison, S. M., Rodgers, J. L. (2016) Casting doubt on the causal link between intelligence and age at first intercourse: A cross-generational sibling comparison design using the NLSY. *Intelligence, 59*, 139-156. <span class="doi">doi: 10.1016/j.intell.2016.08.008</span></cite> (NLSY79; NLSYC)</li>

<li value=65><cite>Brauer, J. R. (2016) [Cultivating Conformists or Raising Rebels? Connecting Parental Control and Autonomy Support to Adolescent Delinquency.](https://dx.doi.org/10.1111/jora.12283) *Journal of Research on Adolescence*. <span class="doi">doi: 10.1111/jora.12283</span></cite> (NLSYC)</li>

<li value=64><cite>Rodgers, J. L., Beasley, W. H., Bard, D. E., Meredith, K. M., Hunter, M., Johnson, A. B., Buster, M., Li,C., May, K. O.,Garrison, S. M., Miller, W. M., van den Oord, E., & Rowe, D. C. (2016) [The NLSYkinship links: Using the NLSY79 and NLSY-Children data to conduct genetically-informed and family-orientedresearch.](https://link.springer.com/article/10.1007/s10519-016-9785-3) *Behavior Genetics*. <span class="doi">doi: 10.1007/s10519-016-9785-3</span></cite> (NLSY79; NLSYC)</li>

<li value=63><cite>Garrison, S. Mason (2016) Multivariate Biometrical Study of the Link between SES and Health Outcomes. Masters Thesis, Vanderbilt University.</cite> (NLSY79)</li>

<li value=62><cite>Connolly, E. J., Beaver, K. M. (2015) [Assessing the Salience of Gene-Environment Interplay in the Development of Anger, Family Conflict, and Physical Violence: A Biosocial Test of General Strain Theory.](https://www.researchgate.net/publication/283794343_Assessing_the_Salience_of_Gene-Environment_Interplay_in_the_Development_of_Anger_Family_Conflict_and_Physical_Violence_A_Biosocial_Test_of_General_Strain_Theory) *Journal of Criminal Justice*. <span class="doi">doi: 10.1016/j.jcrimjus.2015.11.001.</span></cite> (NLSYC)</li>

<li value=61><cite>Connolly, E. J., Beaver, K. M. (2015) Prenatal caloric intake and the development of academic achievement among US children from ages 5 to 14. Child Development, 86 , pp. 1738-1758 </cite> (NLSYC/YA)</li>
  
<li value=60><cite>Connolly, E. J., Schwartz, J. A., Nedelec, J. L., Beaver, K. M., & Barnes, J. C. (2015). [Different Slopes for Different Folks: Genetic Influences on Growth in Delinquent Peer Association and Delinquency During Adolescence.](https://link.springer.com/article/10.1007/s10964-015-0299-8) *Journal of Youth and Adolescence*, 1-15.</cite> (NLSYC)</li>

<li value=59><cite>Vaughan, E. B., Van Hulle, C. A., Beasley, W. H., Rodgers, J. L., & D'Onofrio, B. M. (2015). [Clarifying the associations between age at menarche and adolescent emotional and behavioral problems.](https://pubmed.ncbi.nlm.nih.gov/25687264/) *Journal of Youth and Adolescence, 44*(4), 922-39. <span class="doi">doi: 10.1007/s10964-015-0255-7.</span></cite> (NLSY79; NLSYC)</li>

<li value=58><cite>Jodl, Jacqueline (2015). [Differential Effects of Family Context on Noncognitive Ability and School Performance during Adolescence.](https://academiccommons.columbia.edu/doi/10.7916/D8GQ75BT/download) Dissertation, Columbia University.</cite> (NLSYC)</li>

<li value=57><cite>Rodgers, J. L., Van Hulle, C., D'Onofrio, B., Rathouz, P., Beasley, W., Johnson, A., Waldman, I. & Lahey, B. B. (2015). [Behavior Problems and Timing of Menarche: A Developmental Longitudinal Biometrical Analysis Using the NLSY-Children Data.](https://link.springer.com/article/10.1007/s10519-014-9676-4). *Behavior Genetics, 45*, 51-70.</cite> (NLSYC)</li>

<li value=56><cite>Cheung, A. K., Harden, K. P., & Tucker-Drob, E. M. (2014). [Gene x Environment interactions in early externalizing behaviors: parental emotional support and socioeconomic context as moderators of genetic influences?](https://link.springer.com/article/10.1007/s10519-014-9664-8/fulltext.html) *Behavior Genetics, 44*(5), 468-486.</cite> (NLSYC)</li>

<li value=55><cite>Connolly, Eric J. and Kevin M. Beaver (2014) [Examining the Genetic and Environmental Influences on Self-Control and Delinquency: Results from a Genetically Informative Analysis of Sibling Pairs.](https://pubmed.ncbi.nlm.nih.gov/24142448/) *Journal of Interpersonal Violence, 29*, 707-735.</cite> (NLSYC)</li>

<li value=54><cite>Hunter, Michael D. (2014). [State Space Dynamic Mixture Modeling: Finding People with Similar Patterns of Change.](https://shareok.org/handle/11244/13885) Doctoral Dissertation, University of Oklahoma.</cite> (NLSYC)</li>

<li value=53><cite>Lahey, B. B., D'Onofrio, B. M., Van Hulle, C. A., & Rathouz, P. J. (2014). [Prospective association of childhood receptive vocabulary and conduct problems with self-reported adolescent delinquency: tests of mediation and moderation in sibling-comparison analyses.](https://pubmed.ncbi.nlm.nih.gov/24736982/) *Journal of Abnormal Child Psychology, 42*(8), 1341-1351.</cite> (NLSYC)</li>

<li value=52><cite>Beaver, Kevin M., Eric J. Connolly, Joseph A. Schwartz, Mohammed Said Al-Ghamdi, and Ahmed Nezar Kobeisy (2013) [Genetic and Environmental Contributions to Stability and Change in Levels of Self-Control](https://www.sciencedirect.com/science/article/pii/S004723521300069X). *Journal of Criminal Justice, 41*, 300-308.</cite> (NLSYC)</li>

<li value=51><cite>Goodnight, J. A., D'Onofrio, B. M., Cherlin, A. J., Emery, R. E., Van Hulle, C. A., & Lahey, B. B. (2013). [Effects of Multiple Maternal Relationship Transitions on Offspring Antisocial Behavior in Childhood and Adolescence: A Cousin-Comparison Analysis.](https://link.springer.com/article/10.1007/s10802-012-9667-y) *Journal of Abnormal Child Psychology, 41*(2),185-198.</cite> (NLSY79; NLSYC/YA)</li>

<li value=50><cite>Meredith, K. (2013). [Is AFI all in the family? A multi-level family study of age of first intercourse](https://shareok.org/handle/11244/7913). Doctoral dissertation, University of Oklahoma.</cite> (NLSY79)</li>

<li value=49><cite>Research Media Ltd. (November, 2013). [Family Ties and Kinship Links](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2013/rodgers-2013-international-innovation.pdf). *International Innovation*, 59-61.</cite></li>

<li value=48><cite>D'Onofrio, B. M., Rickert, M. E., L&aring;ngstr&ouml;m, N., Donahue, K. L., Coyne, C. A., Larsson, H., Ellingson, J. M. , Van Hulle, C. A., Iliadou, A. N., Rathouz, P. J., Lahey, B. B., Lichtenstein, P. (2012). [Familial confounding of the association between maternal smoking during pregnancy and offspring substance use and problems: Converging evidence across samples and measures](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3622274/). *Archives of General Psychiatry, 69*, 1140-1150. </cite> (NLSY79; NLSYC/YA)</li>

<li value=47><cite>Dorius, C. (2012). [New approaches to measuring multipartnered fertility over the life course](https://web.archive.org/web/20220611113832/https://www.psc.isr.umich.edu/pubs/pdf/rr12-769.pdf). University of Michigan Population Studies Center Research Report 12-769.</cite> (NLSY79)</li>

<li value=46><cite>Goodnight, J. A., Lahey, B. B., Van Hulle, C. A., Rodgers, J. L., Rathouz, P. J., Waldman, I. D., & D'Onofrio, B. M. (2012). [A quasi-experimental analysis of the influence of neighborhood disadvantage on child and adolescent conduct problems](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3287068/). *Journal of Abnormal Psychology, 121*, 95-108.</cite> (NLSYC/YA)</li>

<li value=45><cite>Harden, K. P., Quinn, P. D., & Tucker-Drob, E. M. (2012). [Genetically influenced change in sensation seeking drives the rise of delinquent behavior during adolescence](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3261521/). *Developmental Science, 15*(1), 150-163.</cite></li>

<li value=44><cite>Jaffee, S., Van Hulle, C., & Rodgers, J L. (2011). [Effects of non-maternal care in the first three years on children's academic skills and behavioral functioning in childhood and early adolescence: A sibling comparison study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3640295/). *Child Development, 84*, 1076-1081.</cite> (NLSY79; NLSYC)</li>

<li value=43><cite>Meredith, K. (2011). Effects of early family environment on age at menarche in the NLSY. Masters thesis, University of Oklahoma. (NLS79).</cite></li>
</ol>


2001 - 2010
-----------------------------

<ol>
<li value=42><cite>Classen, R. (2010). [Measures of the intergenerational transmission of body mass index between mothers and their children in the United States, 1981-2004](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2821676/). *Economics and Human Biology, 8*, 30-43. </cite> (NLSY79; NLSYC/YA)</li>

<li value=41><cite>Dorius, C. (2010). [Does serial parent harm women over the long run?:The link between multiple partner fertility and women's mental and physical health at midlife](https://etda.libraries.psu.edu/catalog/11162). Dissertation, Pennsylvania State University.</cite> (NLSYC)</li>

<li value=40><cite>Hart, S. A., Petrill, S. A., & Kamp Dush, C. M. (2010). [Genetic influences on language, reading, and mathematics skills in a national sample: An analysis using the National Longitudinal Survey of Youth](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3148850/). *Language, Speech, and Hearing Services in Schools, 41*(1), 118.</cite> (NLSY79)</li>

<li value=39><cite>Miller, W. B., Bard, D. E., Pasta, D. J., & Rodgers, J. L. (2010). [Biodemographic modeling of the links between fertility motivation and fertility outcomes in the NLSY79](https://link.springer.com/article/10.1353/dem.0.0107). *Demography, 47*, 393-414.</cite> (NLSY79)</li>

<li value=38><cite>Miller, W. B., Rodgers, J. L., & Pasta, D. (2010). [The fertility motivations of youth predict later fertility outcomes: A prospective analysis of NLSY data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2867342/). *Biodemography and Social Biology, 56*, 1-23.</cite> (NLSY79)</li>

<li value=37><cite>Salsberry, P. J. & Reagan, P.B. (2010). [Effects of heritability, shared environment and non-shared intrauterine conditions on child and adolescent BMI](https://onlinelibrary.wiley.com/doi/abs/10.1038/oby.2009.485). *Obesity, 18*(9), 1775-1780.</cite> (NLSYC)</li>

<li value=36><cite>Lahey, B. B., Van Hulle, C. A., Rathouz, P.J., Rodgers, J. L., D'Onofrio, B. M., & Waldman, I. (2009). [Are oppositional-defiant and hyperactive-inattentive symptoms developmental precursors to conduct problems in late childhood?: Genetic and environmental links](https://link.springer.com/article/10.1007/s10802-008-9257-1). *Journal of Abnormal Child Psychology, 37*, 45-58.</cite> (NLSYC)</li>

<li value=35><cite>Levine, Stephen Z. (2009). Genetic modeling of BMIs: A national representative sample. MA Thesis, Bar Ilan University, Israel.</cite> (NLSY79)</li>

<li value=34><cite>Mendle, J., Harden, K. P., Turkheimer, E., Van Hulle, C. A., D'Onofrio, B. M., Brooks-Bunn, J., Rodgers, J. L., Emery, R. E., & Lahey. B. B. (2009). [Associations between father absence and age of first sexual intercourse](https://srcd.onlinelibrary.wiley.com/doi/full/10.1111/j.1467-8624.2009.01345.x). *Child Development, 80*, 1463-1480.</cite> (NLSY79)</li>

<li value=33><cite>Van Hulle, C. A., Waldman, I. D., D'Onofrio, B. M., Rodgers, J. L., Rathouz, P. J., & Lahey, B. B. (2009). [Developmental structure of genetic influences on antisocial behavior across childhood and adolescence.](https://psycnet.apa.org/journals/abn/118/4/711/) *Journal of Abnormal Psychology, 118*, 711-721.</cite> (NLSYC)</li>

<li value=32><cite>D'Onofrio, B. M., Van Hulle, C.A., Waldman, I. D., Rodgers, J. L., Harden, K. P., Rathouz, P. J., & Lahey, B. B. (2008). [Smoking during pregnancy and offspring externalizing problems: An exploration of genetic and environmental confounds](https://journals.cambridge.org/production/action/cjoGetFulltext?fulltextid=1641968). *Development and Psychopathology, 20*, 139-164. </cite> (NLSY79)</li>

<li value=31><cite>Rodgers, J. L., Bard, D., Johnson, A., D'Onofrio, B., & Miller, W. B. (2008). [The Cross-Generational Mother-Daughter-Aunt-Niece Design: Establishing Validity of the MDAN Design with NLSY Fertility Variables.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2712575/) *Behavior Genetics, 38*, 567-578.</cite> (NLSY79; NLSYC)</li>

<li value=30><cite>D'Onofrio, B.M., Van Hulle, C.A., Waldman, I.D., Rodgers, J.L., Rathouz, P.J., & Lahey, B.B. (2007). [Causal inferences regarding prenatal alcohol exposure and childhood externalizing problems](https://pubmed.ncbi.nlm.nih.gov/17984398/). *Archives of General Psychiatry, 64*, 1296-1304.</cite> (NLSY79; NLSYC)</li>

<li value=29><cite>McCartan, L. M. (2007). [Inevitable, influential, or unnecessary? Exploring the utility of genetic explanation for delinquent behavior.](https://www.sciencedirect.com/science/article/pii/S0047235207000220) *Journal of Criminal Justice, 35*, 219-233.</cite> (NLSYC)</li>

<li value=28><cite>Rodgers, J. L., Bard, D. E., & Miller, W. B. (2007). [Multivariate cholesky models of human female fertility patterns in the NLSY](https://link.springer.com/article/10.1007/s10519-006-9137-9). *Behavior Genetics, 37*, 345-361.</cite> (NLSY79)</li>

<li value=27><cite>Van Hulle, C. A., Rodgers, J. L., D'Onofrio, B. M., Waldman, I. D., & Lahey, B. B. (2007). [Sex differences in the causes of self-reported adolescent delinquency](https://psycnet.apa.org/psycinfo/2007-06673-002). *Journal of Abnormal Psychology, 116*, 236-248.</cite> (NLSYC)</li>

<li value=26><cite>Classen, R. (2006). Essays on the intergenerational transmission of obesity and human capital. Ph.D. Dissertation, University of Wisconsin, Department of Economics.</cite></li>

<li value=25><cite>Rodgers, J. L., Johnson, A., & Bard, D. E. (2005). NLSY-Children/Young Adult (1986-2002) Kinship Linking Algorithm. Unpublished manuscript.</cite></li>

<li value=24><cite>Neiss, M., Rowe, D. C., & Rodgers, J. L. (2002). [Does education mediate the relationship between IQ and age of first birth? A behavior genetic analysis](https://journals.cambridge.org/production/action/cjoGetFulltext?fulltextid=99814). *Journal of Biosocial Science, 34*, 259-275.</cite> (NLSY79)</li>

<li value=23><cite>Bard, D. E. (2001). Common etiology for alcohol and nicotine use: A behavior genetic analysis of liabilities using naturally occurring kinship pairs. Masters Thesis, University of Oklahoma.</cite></li>

<li value=22><cite>Rodgers, J. L., Buster, M., & Rowe, D. C. (2001). [Genetic and environmental influences on delinquency: DF analysis of NLSY kinship data](https://link.springer.com/article/10.1023/A:1011097929954). *Journal of Quantitative Criminology, 17*, 145-168.</cite> (NLSY79)</li>

<li value=21><cite>Rodgers, J. L. & Doughty, D. (2001). [Does having boys or girls run in the family?](https://www.tandfonline.com/doi/abs/10.1080/09332480.2001.10542293) *Chance, 14*, 8-13.</cite> (NLSY79)</li>
</ol>

1994 - 2000
-----------------------------

<ol>
<li value=20><cite>Cleveland, H. H., Jacobson, K. C., Lipinski, J. J. & Rowe, D. C. (2000). [Genetic and shared environmental contributions to the relationship between the home environment and child and adolescent achievement.](https://pubmed.ncbi.nlm.nih.gov/10953940/) *Intelligence, 28*, 69-86.</cite> (NLSYC)</li>

<li value=19><cite>Buster, M. & Rodgers, J. L.(2000). [Genetic and environmental influences on alcohol use: DF analysis of NLSY kinship data](https://journals.cambridge.org/production/action/cjoGetFulltext?fulltextid=9938). *Journal of Biosocial Science, 32*, 177-189.</cite> (NLSY79)</li>

<li value=18><cite>Cleveland, H. H., Wiebe, R. P., van den Oord, E. J. C. G., & Rowe, D. C. (2000). [Behavior problems among children from different family structures: The influence of genetic self-selection](https://srcd.onlinelibrary.wiley.com/doi/abs/10.1111/1467-8624.00182). *Child Development, 71*,733-751.</cite> (NLSYC)</li>

<li value=17><cite>Doughty, D. & Rodgers, J. L. (2000). [Behavior genetic modeling of menarche in U.S. females](https://link.springer.com/chapter/10.1007/978-1-4615-4467-8_11). In J. L. Rodgers, D. Rowe, & W. B. Miller (Eds.) *Genetic influences on fertility and sexuality*, Boston: Kluwer Academic Press.</cite> (NLSY79)</li>

<li value=16><cite>Rodgers, J. L. & Doughty, D. (2000). [Genetic and environmental influences on fertility expectations and outcomes using NLSY kinship data.](https://link.springer.com/chapter/10.1007/978-1-4615-4467-8_6) In J. L. Rodgers, D. Rowe, & W. B. Miller (Eds.) *Genetic influences on fertility and sexuality*, Boston: Kluwer Academic Press.</cite> (NLSY79)</li>

<li value=15><cite>van den Oord, E.J.C.G., Rowe, D.C. (2000). [Racial differences in birth health risk: A quantitative genetic approach](https://link.springer.com/article/10.2307/2648042). *Demography, 37*, 285-298.</cite> (NLSY79)</li>

<li value=14><cite>Rodgers, J. L., Rowe, D. C., & Buster, M. (1999). [Nature, nurture, and first sexual intercourse in the USA: Fitting behavioral genetic models to NLSY kinship data.](https://pubmed.ncbi.nlm.nih.gov/10081235/) *Journal of Biosocial Sciences, 31*.</cite> (NLSY79)</li>

<li value=13><cite>van den Oord, E. J. C. G. & Rowe, D. C. (1999). [A cousin study of associations between family demographic characteristics and children's intellectual ability](https://www.sciencedirect.com/science/article/pii/S0160289699000227). *Intelligence 27*, 251-266.</cite> (NLSYC)</li>

<li value=12><cite>Buster, M. A. (1997). Genetic and environmental influences on alcohol use: DF analysis of NLSY kinship data. Doctoral Dissertation, University of Oklahoma.</cite></li>

<li value=11><cite>Rowe, D. C. & Rodgers, J. L. (1997). [Poverty and behavior: Are environmental measures nature and nurture?](https://www.sciencedirect.com/science/article/pii/S0273229797904342) *Developmental Review, 17*, 358-375.</cite> (NLSYC)</li>

<li value=10><cite>van den Oord, E. J. C. G. & Rowe, D. C. (1997). [Continuity and change in children's maladjustment: A developmental behavior genetic study](https://psycnet.apa.org/journals/dev/33/2/319/). *Developmental Psychology, 33*, 319-332.</cite> (NLSYC)</li>

<li value=9><cite>van den Oord, E. J. C. G. & Rowe, D. C. (1997). [An examination of genotype-environment interactions for academic achievement in an U.S. national longitudinal survey](https://www.sciencedirect.com/science/article/pii/S016028969790043X). *Intelligence, 25*, 205-228.</cite> (NLSYC)</li>

<li value=8><cite>Bjornsdottir, A. (1996). Gender differences in mathematics: Genetic and enviornmental influences with special emphasis on high and low ability. Doctoral Dissertation, University of Oklahoma.</cite></li>

<li value=7><cite>Rodgers, J. L. (1996). NLSY Youth linking algorithm. Unpublished manuscript.</cite> (NLSY79)</li>

<li value=6><cite>Rowe, D. C. & Cleveland, H. H. (1996). [Academic achievement in African -Americans and Whites: Are the developmental processes similar?](https://www.sciencedirect.com/science/article/pii/S0160289696900045) *Intelligence, 23*, 205-228.</cite> (NLSYC)</li>

<li value=5><cite>Rowe, D. C., Linver, M. R., & Rodgers, J. L. (1996). [Delinquency and IQ: Using siblings to find sources of variation](https://psycnet.apa.org/psycinfo/1996-97237-007). Pp. 147-171 in G. Brody (Ed.) *Sibling Relationships: Their Causes and Consequences*. Norwood, NJ: Ablex.</cite> (NLSYC)</li>

<li value=4><cite>Rowe, D. C., Vaszonyi, A. T., & Flannery, D.J. (1995). [Ethnic and racial similarity in developmental process: A study of academic achievement.](https://journals.sagepub.com/doi/abs/10.1111/j.1467-9280.1995.tb00301.x) *Psychological Science, 6*, 33-38.</cite> (NLSYC)</li>

<li value=3><cite>Rodgers, J. L., Rowe, D. C., & Li, C. (1994). [Beyond nature versus nurture: DF analysis of nonshared influences on problem behaviors.](https://psycnet.apa.org:443/journals/dev/30/3/374/) *Developmental Psychology, 30*, 374-384.</cite> (NLSYC)</li>

<li value=2><cite>Rodgers, J. L., Rowe, D. C., & May, K. (1994). [DF analysis of NLSY IQ/achievement data: Nonshared environmental influences.](https://www.sciencedirect.com/science/article/pii/0160289694900116) *Intelligence, 19*, 157-177.</cite> (NLSYC)</li>

<li value=1><cite>Rowe, D. C., Vaszonyi, A. T., & Flannery, D.J. (1994). [No more than skin deep: Ethnic and racial similarity in developmental processes.](https://psycnet.apa.org/journals/rev/101/3/396/) *Psychological Review, 101*, 396-413.</cite> (NLSYC)</li>
</ol>

Recent Presentations by the Team
=============================

**2021: Behavior Genetics Association**

* <cite> Discordant-Sibling Designs and Applications for Differential Psychology. Hannah Robertson and Mason Garrison</cite>

* <cite> Does depression lead to criminal behavior? A sibling comparison design using the NLSY. Emma Sims and Mason Garrison</cite>

* <cite> Liquor Legacies: The impact of parental psychopathology and young adult depression on alcohol use. Rachel Good and Mason Garrison</cite>

* <cite> Breaking down the components of the SES-health gradient with sibling comparisons. Yoo Ri Hwang and Mason Garrison</cite>

* <cite> Perspectives of Gender Roles in the Family versus Personality Traits. Sherry Mao and Mason Garrison</cite>


**2021: American Psychological Association**

* <cite> Exploring the Components of Socio-Economic Status and Their Relationship with Health. Yoo Ri Hwang and Mason Garrison</cite>

**2021: Society for Personality and Social Psychology**

* <cite> Intergenerational consequences of divorce. Kennon Later and Mason Garrison</cite>

* <cite> Gender Roles Attitudes and Personality: A Sibling Comparison Design. Sherry Mao and Mason Garrison</cite>

* <cite> Vaccination and SES: Not such a simple relationship after all. Jonathan Trattner and Mason Garrison</cite>

* <cite> Causal Inference Loves Moms: Extending the Discordant Kinship Design to Parents. Mason Garrison</cite>

* <cite> Examining the relationship between depression and delinquency: A sibling comparison design using the NLSY. Emma Sims and Mason Garrison</cite>

**2020: Behavior Genetics Association**

* <cite> Examining the Causal Link between Divorce and Mental Health of their Offspring Using the Cross-Generational Sibling Comparison Model. Kennon Later and Mason Garrison</cite>

* <cite> Vaccine willingness and socioeconomic status: A biometrically controlled design. Jonathan Trattner and Mason Garrison</cite>

**2019: Behavior Genetics Association**

* <cite> Five ways to analyze 50,000 pairs of related persons in the National Longitudinal Survey of Youth. Mike Hunter</cite>

* <cite> Original and Replication Research with the NLSY79 and NLSY97 Kinship Links. Will Beasley</cite>
%
* <cite> Patterns of Phenotype-Environment Correlation within Cognitive Development. David Bard</cite>

* <cite> The Mediating Impact of Cognitive Ability on the SES-Health Gradient. Patrick O'Keefe</cite>

**2019: Association for Research in Personality**

* <cite>Uncovering the Origins of Age at First Intercourse: Applications of an Extended-Family Behavior Genetic Model. Mason Garrison.</cite>


**2019: Society for Personality and Social Psychology**

* <cite>Uncovering the Biometrical Origins of Age at First Intercourse: Applications of an Extended-Family Behavior Genetic Model. Mason Garrison.</cite>


**2018: Behavior Genetics Association**

* <cite>Responding to a 100-Year-Old Challenge from Fisher: A Biometrical Analysis of Adult Height in the NLSY Data Using Only Cousin Pairs. Joe Rodgers.</cite>

* <cite>AC'RE model: Estimating Rearing Effects without Twins Raised Apart. Mason Garrison.</cite>

* <cite> Bootstrap Confidence Interval Methods for DeFries-Fulker Models. Patrick O'Keefe </cite>

**2017: Society for Personality and Social Psychology**

* <cite>Causal Claims without Experiments: Advances in Discordant Sibling Designs with the SES-health Gradient. Mason Garrison.</cite>

**2016: Society of Multivariate Experimental Psychology**

* <cite>Decomposing the Causes of the SES-Health Gradient with Biometrical Modeling. Mason Garrison.</cite>

**2016: Developmental Methods**

* <cite>[Advances in discordant sibling designs from the NLSY, illustrated with SES and health.](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2016/garrison-devmeth-2016.pdf) Mason Garrison.</cite>

**2015: International Society for Intelligence Research**

* <cite>[Do intelligent girls delay age at first intercourse?: Different results within-families versus between-families.](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2015/rodgers-ISIR-2015.pptx) Joe Rodgers.</cite>

**2015: Association for Research in Personality**

* <cite>[Additive Effects of Maternal Conscientiousness and General Ability on Infant Health.](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2015/garrison-arp-2015.pdf) Mason Garrison.</cite>

**2015: Society for Personality and Social Psychology**

* <cite>[Impact of Adolescent Conscientiousness and Intelligence on Health at Middle Age](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2015/garrison-spsp-2015.pdf): A Sibling Comparison Approach. Mason Garrison.</cite>

**2014: Behavior Genetics Association**

* <cite>[A Dynamic Mixture Biometric Model of Cognitive Development](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2014/hunter-bga-2014.pdf) in the NLSY Children. Mike Hunter.</cite>
* <cite>Family Matters: A Multi-Level Family Study of Age of First Intercourse. David Bard.</cite>
* <cite>[Intelligence and Fertility in the NLSY79 Respondents](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2014/rodgers-bga-2014.pptx): Children of Siblings and Biometrical Models. Joe Rodgers.</cite>

**2013: Society for Adolescent Health and Medicine**

* <cite>[Psychosocial Predictors Of Adolescent Sexual Risk Behavior](https://www.researchgate.net/publication/260010468_Psychosocial_Predictors_of_Adolescent_Sexual_Risk_Behavior_A_Quasi-Experimental_Analysis_in_a_Nationally_Representative_Sample_of_American_Youths): A Quasi-experimental Analysis In A Nationally Representative Sample Of American Youths. Kelly Donahue, Carol Van Hulle, Joe Rodgers, Brian D'Onofrio.</cite>

**2013: Behavior Genetics Association**

* <cite>[NLSY Kinship Links](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2013/beasley-bga-2013.pptx): Creating Biometrical Design Structures from Cross-Generational Data. Will Beasley.</cite>

**2012: Behavior Genetics Association**

* <cite>[The 2012 National Longitudinal Survey of Youth Kinship Links](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2012/rodgers-bga-2012.pptx): Conducting Behavior Genetic Research Using the NLSY79 and NLSY-Children Data. Joe Rodgers.</cite>
* <cite>[NlsyLinks](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2012/beasley-bga-2012.pptx): An R Package Facilitating BG Research with the NLSY. Will Beasley.</cite>
* <cite>[Biometric Analysis of Complex NLSY Pedigrees](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2012/bard-bga-2012.pptx): Introducing a Conditional Autoregressive Biometric (CARB) Mixed Model. David Bard.</cite>
* <cite>[Multivariate Models of BMI, Intelligence, and Fertility](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2012/meredith-bga-2012.pptx) Using the NLSY-Children Kinship Links. Kelly Meredith.</cite>
* <cite>[The 2012 National Longitudinal Survey of Youth Kinship Links](https://github.com/nlsy-links/NlsyLinks/blob/master/vignettes/publications/2012/donofrio-bga-2012.pptx): A Discussion. Brian D'Onofrio.</cite>

General NLSY Articles
=============================

A larger, searchable list of research using the NLSY datasets is maintained at [nlsinfo.org](https://nlsinfo.org/bibliography-start).

# Current Documentation, Vignettes, and User Support
Please see the provided entries on the [Research Software and Support](https://nlsy-links.github.io/NlsyLinks/articles/software-and-support.html) page.

# Software Packages

* <cite> Garrison, S. M., Trattner, J., and Ream, C. (2021). discord: Functions for Discordant Kinship Modeling R package [CRAN.R-project.org/package=discord](https://CRAN.R-project.org/package=discord)

------
Compiled by [Joe Rodgers](https://www.vanderbilt.edu/psychological_sciences/bio/joe-rodgers), [Will Beasley](https://scholar.google.com/citations?user=ffsJTC0AAAAJ&hl=en), [Mason Garrison](https://www.smasongarrison.com/), and [Patrick O'Keefe](https://www.vanderbilt.edu/psychological_sciences/bio/patrick-okeefe)
