---
title: 'NlsyLinks: An R Package for Utilities and Kinship Information'
output:
  rmarkdown::html_vignette:
    keep_md: TRUE
tags:
  - R
  - pedigrees
  - behavior genetics
authors:
  - name: S. Mason Garrison
    orcid: 0000-0002-4804-6003
    affiliation: 1
  - name: William Howard Beasley
    orcid: 0000-0002-5613-5006
    affiliation: 4
  - name: Michael D. Hunter
    orcid: 0000-0002-3651-6709
    affiliation: 2
  - name: David Bard
    affiliation: 6
  - name: Patrick O'Keefe
    orcid: 0000-0002-5343-0130
    affiliation: 7
  - name: Kelly Meredith Williams
    affiliation: 3
  - name: Joseph Lee Rodgers
    orcid: 0000-0002-8615-6713
    affiliation: 4, 5
affiliations:
  - name: Department of Psychology, Wake Forest University, North Carolina, USA
    index: 1
  - name: Department of Human Development and Family Studies, Pennsylvania State University, Pennsylvania, USA
    index: 2
  - name: Department PLACEHOLDER, University PLACEHOLDER, CITY, USA
    index: 3
  - name: Department of Psychology, University of Oklahoma, Oklahoma, USA
    index: 4
  - name: Department of Psychology and Human Development, Vanderbilt University, Tennessee, USA
    index: 5
  - name: Department PLACEHOLDER, University PLACEHOLDER, CITY, USA
    index: 6
  - name: Department PLACEHOLDER, University PLACEHOLDER, CITY, USA
    index: 7

date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: paper.bib
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, echo=FALSE}
options(rmarkdown.html_vignette.check_title = FALSE)
```


<!--Guidance 
JOSS welcomes submissions from broadly diverse research areas. For this reason, we require that authors include in the paper some sentences that explain the software functionality and domain of use to a non-specialist reader. We also require that authors explain the research applications of the software. The paper should be between 250-1000 words. Authors submitting papers significantly longer than 1000 words may be asked to reduce the length of their paper.
Your paper should include:

A list of the authors of the software and their affiliations, using the correct format (see the example below).
A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
A Statement of need section that clearly illustrates the research purpose of the software and places it in the context of related work.
A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
Acknowledgment of any financial support.
-->

# Summary

<!--  A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience. -->




# Statement of need
<!-- A Statement of need section that clearly illustrates the research purpose of the software and places it in the context of related work. -->


## Features

The `NlsyLinks` package offers features tailored for XXXXXXX. These features are grouped under NUMBER main categories, mirroring the structure presented in our vignettes.

### FEATURE A:

-   FEATURE A.1: 

-   FEATURE A.2: 

-   FEATURE A.3:


### Feature B:

-   FEATURE B.1: 

-   FEATURE B.2: 



<!-- Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.-->

Collectively, these tools provide a valuable resource for behavior geneticists and others who work with extended family data. They were developed as part of a grant and have been used in several ongoing projects and theses.

# Availability

The `NlsyLinks` package is open-source and available on both GitHub at [https://github.com/nlsy-links/NlsyLinks](https://github.com/nlsy-links/NlsyLinks) and the Comprehensive R Archive Network (CRAN) at [https://cran.r-project.org/package=NlsyLinks](https://cran.r-project.org/package=NlsyLinks). It is licensed under the GNU General Public License.

# Acknowledgments

Recent work on the NLSY Kinship links has been supported by NIH Grant R01-HD065865 (May 1, 2011 to December 31, 2014; Joe Rodgers, PI) and NIH Grant R01-HD087395 (May 1, 2017 to April 30, 2021). Previous kinship linking activity was supported by two previous NIH grants, the first in the 1990s, the second in the early 2000s.

# References
