# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches: [main, master]
    paths:
      - '**.R'
      - '**.Rd'
      - '**.Rmd'
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release', rtools: ''}
          - {os: windows-latest, r: 'release', rtools: '42'}
          - {os: ubuntu-latest, r: 'devel', rtools: '', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release', rtools: ''}
          - {os: ubuntu-latest, r: 'oldrel-1', rtools: ''}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: |
            any::rcmdcheck
          upgrade: 'TRUE'
          needs: check
          
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

